{ lib
, six
, pkgs
, targets
}:
six.mkFunnel {
  passthru.after = [ targets.global.coldplug ];
  run = pkgs.writeScript "run" ''
#!${pkgs.runtimeShell}
exec 2>&1
modprobe w83795

export PATH=$PATH:${with pkgs; lib.makeBinPath [ gnugrep gnused ]}

# fancontrol gets upset if device paths change, and for some reason the kgpe
# motherboard randomly picks between two possibilities.  So we try both.

CPU0=$(grep -H k10temp /sys/class/hwmon/hwmon?/name | sed 's_.*hwmon/__' | sed 's_/.*__' | head -n1 | tail -n1)
CPU1=$(grep -H k10temp /sys/class/hwmon/hwmon?/name | sed 's_.*hwmon/__' | sed 's_/.*__' | head -n2 | tail -n1)
FANS=$(cd /sys/bus/i2c/drivers/w83795/1-002f/; ls hwmon | sed 's_/__')

echo CPU0=''${CPU0}
echo CPU1=''${CPU1}
echo FANS=''${FANS}

BASE=/sys/devices/pci0000:00/0000:00:14.0/i2c*/*-002f

echo 1 > ''${BASE}/pwm1_enable
#test -e ''${BASE}/hwmon/hwmon6/pwm1_enable && echo 1 > ''${BASE}/hwmon/hwmon6/pwm1_enable

    echo
    temp_southbridge=$(sensors w83795g-i2c-1-2f | grep temp1: | sed s_[^C]*\+__ | sed s_\\..*__) 
    temp_cpu1=$(sensors k10temp-pci-00d3 | grep temp1: | sed s_[^C]*\+__ | sed s_\\..*__) 
    temp_cpu2=$(sensors k10temp-pci-00c3 | grep temp1: | sed s_[^C]*\+__ | sed s_\\..*__)
#    temp_southbridge=$(( $(cat ''${TEMP_SOUTHBRIDGE}/temp_cpu1_input) / 1000 ))
#    temp_cpu1=$(( $(cat ''${CPU1}/temp_cpu1_input) / 1000 ))
#    temp_cpu2=$(( $(cat ''${CPU2}/temp_cpu1_input) / 1000 ))
#    echo "cpu3        = "$(( $(cat ''${CPU3}/temp_cpu1_input) / 1000 ))
#    echo "cpu4        = "$(( $(cat ''${CPU4}/temp_cpu1_input) / 1000 ))
#    echo "southbridge = "''${temp_southbridge}""
    echo "southbridge = "''${temp_southbridge}" (ignored)"
    temp_southbridge=$(( ''${temp_southbridge} - 20 ))
#    echo "            = "''${temp_southbridge}" (normalized)"
    echo "cpu1        = "''${temp_cpu1}
    echo "cpu2        = "''${temp_cpu2}
    temp=$(( ''${temp_cpu1} > ''${temp_cpu2} ? ''${temp_cpu1} : ''${temp_cpu2} ))
#    temp=$(( ''${temp}  >''${temp_southbridge} ? ''${temp}   : ''${temp_southbridge} ))
    echo "temp        = "''${temp}
#    maxtemp=35
    maxtemp=40
#    maxtemp=45
#    maxtemp=50
    mintemp=10
    maxpwm=255
    minpwm=30
#    minpwm=80
#    minpwm=120
#    minpwm=180
#    minpwm=200
    pwm_range=$(( ''${maxpwm} - ''${minpwm} ))
    temp_range=$(( ''${maxtemp} - ''${mintemp} ))
    temp=$(( ''${temp} - ''${mintemp} ))
    pwm=$(( ( ( ''${pwm_range} * 1000 * ''${temp} * ''${temp}) / ''${temp_range} / ''${temp_range} ) / 1000 + ''${minpwm} ))
    pwm=$(( ''${pwm} > ''${maxpwm} ? ''${maxpwm} : ''${pwm} ))
    pwm=$(( ''${pwm} < ''${minpwm} ? ''${minpwm} : ''${pwm} ))
#    pwm=255
    echo "pwm         = "''${pwm}
    echo ''${pwm} > ''${BASE}/pwm1

##############################################################################
    
#    temp_radeon=$(sensors radeon-pci-0100  | grep temp1: | sed s_[^C]*\+__ | sed s_\\..*__)
#    echo "radeon      = "''${temp_radeon}""
#    temp=''${temp_radeon}
#    maxtemp=50
#    mintemp=39
#    maxpwm=255
##    minpwm=30
#    minpwm=20
#    pwm_range=$(( ''${maxpwm} - ''${minpwm} ))
#    temp_range=$(( ''${maxtemp} - ''${mintemp} ))
#    temp=$(( ''${temp} - ''${mintemp} ))
#    pwm=$(( ( ( ''${pwm_range} * 1000 * ''${temp}) / ''${temp_range} ) / 1000 ))
#    pwm=$(( ''${pwm} > ''${maxpwm} ? ''${maxpwm} : ''${pwm} ))
#    pwm=$(( ''${pwm} < ''${minpwm} ? ''${minpwm} : ''${pwm} ))
##    pwm=255
#    echo "pwm         = "''${pwm}
#    echo ''${pwm} > ''${BASE}/hwmon/hwmon6/pwm1

    echo
exec sleep 3  # does not return

                           
exec /usr/sbin/fancontrol /dev/stdin <<EOF
# Configuration file generated by pwmconfig, changes will be lost
INTERVAL=10
DEVPATH=hwmon0=devices/pci0000:00/0000:00:18.3 hwmon2=devices/pci0000:00/0000:00:1a.3 hwmon7=devices/pci0000:00/0000:00:14.0/i2c-1/1-002f
DEVNAME=hwmon0=k10temp hwmon2=k10temp hwmon7=w83795g
FCTEMPS=hwmon7/device/pwm2=hwmon0/temp1_input hwmon7/device/pwm1=hwmon2/temp1_input
FCFANS=hwmon7/device/pwm2=hwmon7/device/fan2_input+hwmon7/device/fan1_input hwmon7/device/pwm1=hwmon7/device/fan2_input+hwmon7/device/fan1_input
MINTEMP=hwmon7/device/pwm2=15 hwmon7/device/pwm1=15
MAXTEMP=hwmon7/device/pwm2=30 hwmon7/device/pwm1=30
MINSTART=hwmon7/device/pwm2=150 hwmon7/device/pwm1=150
MINSTOP=hwmon7/device/pwm2=0 hwmon7/device/pwm1=0
# Configuration file generated by pwmconfig, changes will be lost
#INTERVAL=1
#DEVPATH=''${CPU0}=$(readlink /sys/class/hwmon/''${CPU0} | sed 's_^.*devices/_devices/_' | sed s_/hwmon.*__) ''${CPU1}=$(readlink /sys/class/hwmon/''${CPU1} | sed 's_^.*devices/_devices/_' | sed s_/hwmon.*__) ''${FANS}=$(readlink /sys/class/hwmon/''${FANS} | sed 's_^.*devices/_devices/_' | sed s_/hwmon.*__)
#DEVNAME=''${CPU0}=k10temp ''${CPU1}=k10temp ''${FANS}=w83795g
#FCTEMPS=''${FANS}/device/pwm2=''${CPU0}/temp1_input ''${FANS}/device/pwm1=''${CPU1}/temp1_input
#FCFANS=''${FANS}/device/pwm2=''${FANS}/device/fan2_input+''${FANS}/device/fan1_input ''${FANS}/device/pwm1=''${FANS}/device/fan2_input+''${FANS}/device/fan1_input
#MINTEMP=''${FANS}/device/pwm2=20 ''${FANS}/device/pwm1=20
#MAXTEMP=''${FANS}/device/pwm2=90 ''${FANS}/device/pwm1=90
#MINSTART=''${FANS}/device/pwm2=10 ''${FANS}/device/pwm1=01MINPWM=''${FANS}/device/pwm2=10  ''${FANS}/device/pwm1=10
#MAXPWM=''${FANS}/device/pwm2=20 ''${FANS}/device/pwm1=20
#MINSTOP=''${FANS}/device/pwm2=0 ''${FANS}/device/pwm1=0
EOF
  '';
}
